image:
  file: .gitpod.dockerfile

# tasks:
#   - command: |

#       mysql -e "CREATE DATABASE todos"
#       mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'secret';"